"""Build compact Bengaluru geometry for Ten Rupee Estates from BBMP ward boundaries.

Source: DataMeet Municipal_Spatial_Data, Bangalore/BBMP.geojson (243 wards, CC BY 4.0).
Output: geo.js with simplified ward polygons and a cell -> ward lookup for the plot grid.
"""
import json, sys, base64

SRC, OUT = sys.argv[1], sys.argv[2]
LAT0, LNG0, D = 13.145, 77.455, 0.0015          # grid origin (top-left) and cell size in degrees
ROWS, COLS = 210, 222
Q = 1e4                                           # coordinate quantisation (~11 m)
TOL = 0.00025                                     # simplification tolerance in degrees (~27 m)

def rdp(pts, eps):
    if len(pts) < 3: return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1; n = (dx*dx + dy*dy) ** .5 or 1e-12
    dmax, idx = 0, 0
    for i in range(1, len(pts) - 1):
        d = abs(dy*pts[i][0] - dx*pts[i][1] + x2*y1 - y2*x1) / n
        if d > dmax: dmax, idx = d, i
    if dmax > eps:
        return rdp(pts[:idx+1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]

def inside(x, y, ring):
    c = False; j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i]; xj, yj = ring[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi: c = not c
        j = i
    return c

feats = json.load(open(SRC))['features']
wards, polys = [], []
for f in feats:
    g = f['geometry']
    parts = [g['coordinates']] if g['type'] == 'Polygon' else g['coordinates']
    rings = []
    for part in parts:
        outer = part[0]
        pts = [tuple(p[:2]) for p in outer]
        if pts[0] == pts[-1]: pts = pts[:-1]
        h = len(pts) // 2                        # closed rings: simplify each half so the endpoints differ
        s = rdp(pts[:h+1], TOL)[:-1] + rdp(pts[h:] + [pts[0]], TOL)[:-1]
        if len(s) >= 4: rings.append(s)
    name = f['properties']['KGISWardName'].replace(' Ward', '').replace(' ward', '').strip()
    wards.append({'n': name, 'no': f['properties']['KGISWardNo'], 'r': rings})
    polys.append(rings)

# cell -> ward index (+1), 0 = outside BBMP limits
cells = bytearray(ROWS * COLS)
for wi, rings in enumerate(polys):
    for ring in rings:
        xs = [p[0] for p in ring]; ys = [p[1] for p in ring]
        r0 = max(0, int((LAT0 - max(ys)) / D)); r1 = min(ROWS - 1, int((LAT0 - min(ys)) / D))
        c0 = max(0, int((min(xs) - LNG0) / D)); c1 = min(COLS - 1, int((max(xs) - LNG0) / D))
        for r in range(r0, r1 + 1):
            y = LAT0 - (r + .5) * D
            for c in range(c0, c1 + 1):
                if cells[r*COLS + c]: continue
                if inside(LNG0 + (c + .5) * D, y, ring): cells[r*COLS + c] = wi + 1

# delta-encode quantised rings
enc = []
for w in wards:
    rr = []
    for ring in w['r']:
        flat, px, py = [], 0, 0
        for x, y in ring:
            qx, qy = round(x * Q), round(y * Q)
            flat += [qx - px, qy - py]; px, py = qx, qy
        rr.append(flat)
    enc.append([w['n'], w['no'], rr])

inside_n = sum(1 for v in cells if v)
js = ("// Generated by tools/build_geo.py from BBMP ward boundaries (DataMeet, CC BY 4.0). Do not edit by hand.\n"
      f"const GEO={{lat0:{LAT0},lng0:{LNG0},d:{D},rows:{ROWS},cols:{COLS},q:{Q},\n"
      f"wards:{json.dumps(enc, separators=(',', ':'))},\n"
      f"cells:\"{base64.b64encode(bytes(cells)).decode()}\"}};\n")
open(OUT, 'w').write(js)
print(f"wards={len(wards)} points={sum(len(r) for w in wards for r in w['r'])} cells_inside={inside_n} bytes={len(js)}")
